jobs:
######################### NATIVE WAR CI/CD JOBS #########################
# manifest that defines the Native WAR service definition
 - name: demo_war_manifest
   type: manifest
   steps:
     - IN: demo_war_s3
     - IN: demo_war_params

# runCLI job that deploys artifact in S3 to EC2
 - name: demo_war_test_deploy
   type: runCLI
   steps:
     - IN: demo_war_manifest
       force: true
     - IN: demo_war_s3
     - IN: demo_war_test_cls
     - IN: demo_war_awscli
     - IN: demo_war_params
     # - IN: demo_war_params_build
     - TASK:
       - script: echo "Latest build is in - "$DEMO_WAR_S3_SOURCENAME/$DEMO_WAR_S3_VERSIONNAME
       # - script: "aws command to call Opsworks"  
       - aws s3 cp s3://$DEMO_WAR_S3_SOURCENAME/$DEMO_WAR_S3_VERSIONNAME /tmp/shippable/HelloWorld.war
       - script: echo -e "$DEMO_WAR_TEST_CLS_INTEGRATION_PRIVATEKEY" > ~/.ssh/ec2-node && sudo chmod 600 ~/.ssh/ec2-node
       - script: cat ~/.ssh/ec2-node
       - script: scp -i ~/.ssh/ec2-node /tmp/shippable/HelloWorld.war shippable@ec2-54-204-165-30.compute-1.amazonaws.com@ec2-54-204-165-30.compute-1.amazonaws.com:/opt/tomcat/HelloWorld.war
